matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_install:
        - cd advert-board-backend
        - chmod +x mvnw

    - language: node_js
      node_js:
        - "11.10.0"
      cache:
        directories:
        - node_modules
      before_script:
        - cd advert-board-frontend
      script:
        - npm test